version: "3.3"
services:
  jira:
    image: dchevell/jira-software:latest
    volumes:
    - type: volume
      source: ./docker/volumes/jira
      target: /var/atlassian/application-data/jira
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
      mode: host
  confluence:
    image: atlassian/confluence-server:latest
    volumes:
      - type: volume
        source: ./docker/volumes/confluence
        target: /var/atlassian/application-data/confluence
    ports:
      - target: 8090
        published: 8090
        protocol: tcp
        mode: host
      - target: 8091
        published: 8091
        protocol: tcp
        mode: host
