version: "3.3"
services:
  jira:
    image: atlassian/jira-software:latest
    volumes:
      - ./docker/volumes/jira:/var/atlassian/application-data/jira
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
  confluence:
    image: atlassian/confluence-server:latest
    volumes:
      - ./docker/volumes/confluence:/var/atlassian/application-data/confluence
    ports:
      - target: 8090
        published: 8090
        protocol: tcp
        mode: host
      - target: 8091
        published: 8091
        protocol: tcp
        mode: host
