# release workflow

name: release

# Controls when the action will run.
on:
  # Triggers the workflow on push but only for the master branch
  push:
    tags: [ 'v*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Create release package
        run: |
          release_version="${GITHUB_REF#refs/*/v}"
          cp ./build/distributions/atl-export.zip ./atl-export-${release_version}.zip
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./atl-export-*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
